# Setting coverage targets per flag
coverage:
  round: down
  range: 70..90
  precision: 2
  status:
    patch: off
    project:
      default: off
      t8:
        threshold: 1%
        flags:
          - t8

flags:
  t8:
    paths:
      # filter the folder(s) you wish to measure by that flag
      - src

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: true # only post the comment if coverage changes

github_checks:
  annotations: false

flag_management:
  default_rules:
    carryforward: false
