#!/bin/sh

# only build basic pkg

lerna run build --stream --scope @antv/narrative-text-schema \
                         --scope @antv/word-scale-chart \

wait
lerna run build --stream --scope @antv/narrative-text-vis
